apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: k3d-local-registry:5000/todo-backend:latest
          imagePullPolicy: Always
          env:
            - name: APPLICATION_TYPE
              value: "backend"
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: BACKEND_PORT
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: DATABASE_URL
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: POSTGRES_DB
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: POSTGRES_PORT
