apiVersion: v1
kind: ConfigMap
metadata:
  name: the-project-config
  namespace: project
data:
  # Frontend config
  APP_PORT: "3001"
  BACKEND_URL: "http://todo-backend:3000"
  IMAGE_CACHE_TIME: "600"
  PICSUM_URL: "https://picsum.photos/1200"
  
  # Backend config
  BACKEND_PORT: "3000"
  DATABASE_URL: "host=postgres-todos-0.postgres-todos-headless user=postgres password=postgres dbname=todos port=5432"
  POSTGRES_HOST: "postgres-todos-0.postgres-todos-headless"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "todos"
  POSTGRES_PORT: "5432"
