apiVersion: v1
kind: ConfigMap
metadata:
  name: the-project-config
  namespace: project
data:
  # Frontend config
  APP_PORT: "3001"
  BACKEND_URL: "http://todo-backend:3000"
  IMAGE_CACHE_TIME: "600"
  PICSUM_URL: "https://picsum.photos/1200"
  
  # Backend config
  BACKEND_PORT: "3000"
