apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      volumes:
        - name: the-project-volume
          persistentVolumeClaim:
            claimName: the-project-pv-claim
      containers:
        - name: the-project
          image: k3d-local-registry:5000/todo-app:latest
          env:
            - name: PORT
              value: "3001"
            - name: APPLICATION_TYPE
              value: "app"
            - name: BACKEND_URL
              value: "http://todo-backend:3000"
          volumeMounts:
            - name: the-project-volume
              mountPath: /opt/project
