apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      volumes:
        - name: the-project-volume
          persistentVolumeClaim:
            claimName: the-project-pv-claim
      containers:
        - name: the-project
          image: k3d-local-registry:5000/todo-app:latest
          imagePullPolicy: Always
          env:
            - name: APPLICATION_TYPE
              value: "app"
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: APP_PORT
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: BACKEND_URL
            - name: IMAGE_CACHE_TIME
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: IMAGE_CACHE_TIME
            - name: PICSUM_URL
              valueFrom:
                configMapKeyRef:
                  name: the-project-config
                  key: PICSUM_URL
          volumeMounts:
            - name: the-project-volume
              mountPath: /opt/project
