apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      volumes:
        - name: the-project-volume
          persistentVolumeClaim:
            claimName: the-project-pv-claim
      containers:
        - name: the-project
          image: the-project:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "8080"
          volumeMounts:
            - name: the-project-volume
              mountPath: /opt/project
