[package]
name = "ping_pong"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
deadpool-postgres = "0.14.1"
native-tls = "0.2.14"
tokio = { version = "1.48.0", features = ["full"] }
tokio-postgres = "0.7.16"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
