[package]
name = "the_project"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
reqwest = "0.12.24"
serde =  { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
