apiVersion: v1
kind: Service
metadata:
  name: log-output-service
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - name: http
      protocol: TCP
      port: 5678
      targetPort: 5678
      nodePort: 30678
